### ISSUE TITLE
The Bluetooth icon sometimes seems to be cut off

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/wingpanel-indicator-bluetooth#106] opened 2020-03-13 12:00 UTC
![Screenshot](https://user-images.githubusercontent.com/46536067/76619152-1f800b00-6522-11ea-925e-4910a98d7ced.png)

I use a stable standard system without any changes and always with the latest updates. Unfortunately I cannot say (yet) how the issue can be reproduced.

**Comment by janxkoci** [comment] 2020-03-26 15:49
I can semi-reproduce this issue to some extent - it always occurs after I suspend my laptop (by closing a lid). It doesn't appear everytime though (hence "semi-reproduce"), but I believe somewhere there is the trigger.

I also made a bunch of screenshots in the past few days with different variants of the "cut off", including "total" case:

![Snímek z 2020-03-24 11-31-58](https://user-images.githubusercontent.com/19331850/77666602-70135180-6f81-11ea-9ff7-67756c7f7821.png)

![Snímek z 2020-03-24 15-31-08](https://user-images.githubusercontent.com/19331850/77666607-71447e80-6f81-11ea-96fa-b43a44dc9330.png)

![Snímek z 2020-03-20 12-24-18](https://user-images.githubusercontent.com/19331850/77666727-989b4b80-6f81-11ea-88cc-6eac506d0cb6.png)

![Snímek z 2020-03-24 20-24-55](https://user-images.githubusercontent.com/19331850/77666609-71dd1500-6f81-11ea-98b6-d846e6dd562c.png)

**Comment by ryonakano** [comment] 2020-03-27 06:23
Thank you for your reports, but I'll close this issue as a duplicate of #89.

**Closed by ryonakano** 2020-03-27 06:23 UTC

**Comment by 4jNsY6fCVqZv** [comment] 2020-03-27 09:27
@ryonakano What makes you think that disappearance and being cut off have the same source?
And what ideas do you have for solving this problem?

**Comment by janxkoci** [comment] 2020-03-27 09:32
@4jNsY6fCVqZv From my screenshots you can see that I experience both states after the same trigger. The indicator is always there, just the icon is either fully or partially missing. The underlying issue is clearly the same.

**Comment by 4jNsY6fCVqZv** [comment] 2020-03-27 09:39
In this case, does it matter to you whether you have Bluetooth enabled or disabled?
For example, I never use Bluetooth.

**Comment by janxkoci** [comment] 2020-03-27 09:47
I use it sometimes for earphones. As I said, I can always fix the issue by killing wingpanel. I usually use the [Monitor app](http://appcenter.elementary.io/com.github.stsdc.monitor/) as it makes it super easy.

**Comment by 4jNsY6fCVqZv** [comment] 2020-03-27 09:50
Yeah, that's not a fix in my perspective, though. It can't be that users always have to know and end their PIDs manually.

**Comment by janxkoci** [comment] 2020-03-27 10:14
> Yeah, that's not a fix in my perspective, though.

I agree.

> It can't be that users always have to know and end their PIDs manually.

I don't need PID - in the Monitor app it's easy to kill app by name, as it lists the top level parent processes. It's really neat.
