### ISSUE TITLE
No bluetooth icon

### ISSUE THREAD

**Issue by alvin-gonzalez-o2o** [elementary/wingpanel-indicator-bluetooth#120] opened 2020-07-01 10:31 UTC
The bluetooth icon just disappeared from the top menu ... I tried restarting bluetooth services but nothing works. I am using os version 5.1.5

**Comment by ryonakano** [comment] 2020-07-01 10:59
Thank you for reporting, but I'll close this issue as a duplicate of #89.

**Closed by ryonakano** 2020-07-01 10:59 UTC
