### ISSUE TITLE
Can't add Bluetooth devices (e.g. mouse) during OS installation

### ISSUE THREAD

**Issue by 413Michele** [elementary/wingpanel-indicator-bluetooth#165] opened 2021-08-11 14:05 UTC
## What Happened

When installing eOS 6 directly without entering Demo mode, you can see the Bluetooth indicator but not add any device, because you can't open the Bluetooth settings. This is a problem if you need to connect a mouse or any other device before finishing the installation.

This behaviour might be due to not being logged in, as Wingpanel in the Greeter doesn't allow to access BT settings either.

## Expected Behavior
The user should be able to pair bluetooth devices at installation time.

## Steps to Reproduce

1. Burn ISO to USB and boot
2. Start the installation process
3. Click on the Bluetooth indicator
4. No way to access BT settings or pair devices

## Platform Information

Elementary OS 6 Stable release ISO

**Comment by danrabbit** [comment] 2021-08-11 17:33
Hey thanks for your issue report! This sounds like a duplicate of https://github.com/elementary/wingpanel-indicator-bluetooth/issues/82

Closing as duplicate

**Closed by danrabbit** 2021-08-11 17:33 UTC
