### ISSUE TITLE
Bluetooth auto enable on screen lock

### ISSUE THREAD

**Issue by chauhankiran** [elementary/wingpanel-indicator-bluetooth#40] opened 2018-03-14 18:32 UTC
Each time you manually have to disable Bluetooth after login back from screen lock.

Step to reproduce:

Login > Disable Bluetooth > Click on shutdown icon > Select "lock"

This will automatically enable Bluetooth and each time after login back from lock, have to again disable Bluetooth.

**Comment by danrabbit** [comment] 2018-04-09 17:43
This seems to be a duplicate of #23

**Closed by danrabbit** 2018-04-09 17:43 UTC
