### ISSUE TITLE
Mouse in "Not connected" status even when connected

### ISSUE THREAD

**Issue by AlonsoEnrique** [elementary/wingpanel-indicator-bluetooth#28] opened 2017-07-19 20:35 UTC
![screenshot from 2017-07-19 15-26-56](https://user-images.githubusercontent.com/1877511/28388330-04b8c40e-6c98-11e7-91e6-68cf321dfca8.png)

**Comment by peteruithoven** [comment] 2019-02-10 21:22
Thanks for the report! I'm afraid I can't reproduce this. Seeing it's been a while I'm going to close it. Please reopen when it's still happening.

**Closed by peteruithoven** 2019-02-10 21:22 UTC
